name: Smoke SDTM

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install package for CLI entrypoint
          pip install -e .

      - name: Run smoke test
        run: |
          mkdir -p output/smoke
          bash scripts/smoke_sdtm.sh

      - name: Upload smoke outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-output
          path: |
            output/smoke/**
            output/*.csv
            output/*.dataset.json
